Vedant's first contribution
jedieaston/WinGetHelpers pull request #4
Opened 2021-10-24 05:55 UTC by vedantmgoyal2009

I kept the PR title so because this PR does many things which cannot be described in the title.

2021-10-24 06:24 UTC, vedantmgoyal9 commented
@jedieaston Would you like to give it a go?

2021-10-24 22:06 UTC, jedieaston commented
I can attempt to review it sometime this week, but can you summarize what you did? Since I don't have a test suite I can't automatically review your changes to make sure functionality wasn't broken.

2021-10-25 08:29 UTC, vedantmgoyal9 commented
- Update documentation (README.md)
- Add CODEONWERS so that we don't need to comment "@jedieaston please review/take a look upon it" and can directly request a review from you
- Add PSScriptAnalyser to ensure code quality
- Add GitHub Pages theme "Cayman" because it makes documentation easier to read.
- OTBS indentation for psm1 and psd1 files

2021-11-01 15:21 UTC, vedantmgoyal2009 commented
@jedieaston just writing this comment to remind you that you've to review it.

2021-11-14 04:27 UTC, vedantmgoyal2009 commented
@jedieaston Is there anything I've done wrong? I don't think I've made any BREAKING changes.

2021-11-14 19:25 UTC, jedieaston requested changes
I reviewed it, much of it seems fine but somewhat unnecessary (that's a lot of spacing). If you make the suggested changes I'll approve this.

2021-11-14 19:25 UTC, jedieaston commented on _config.yml
> +theme: jekyll-theme-cayman
I'm not a huge fan of this theme, and I'm not quite sure why it's needed? Pages isn't configured for this repository.

2021-11-14 19:25 UTC, jedieaston commented on WinGetHelpers.psm1
> +        ManifestVersion   = "1.0.0";
Why so much spacing? I don't know how much having the equal signs being in parallel is important (and I'm not sure I'll be paying attention when changing this code later).

2021-11-14 19:25 UTC, jedieaston commented on .github/workflows/powershell-analysis.yml
> +name: PSScriptAnalyzer
I don't know why we need this. I understand what ScriptAnalyzer does, but I don't feel like troubleshooting it if it blows up. 

If someone's using this for a production level service and feels like there are issues with the PowerShell scripts that ScriptAnalyzer would find, they should probably rewrite it themselves. I wrote this to get a better understanding of PoSH, not to be a battle-hardened super secure way of updating manifests (that's `wingetcreate`'s job!).

2021-11-14 19:25 UTC, jedieaston commented on README.md
> -__Now updated for 1.0 manifests!__
Please put this message back.

2021-11-14 19:25 UTC, jedieaston commented on README.md
> -These are some cmdlets I hastely made to help support microsoft/winget-pkgs. Maybe they'll help you too.
Please put this message back.

2021-11-14 19:25 UTC, jedieaston commented on README.md
> -So before you download this module and put it in your modules folder, make sure to do ` Install-Module powershell-yaml; Install-Module -Name 'Carbon' `
Please put this message back. People who want to use this may not be familiar with PowerShell.

2021-11-14 19:25 UTC, jedieaston commented on README.md
> -I'm not very good at PowerShell, which is why it looks so bad, but all of these work on my machine(tm) so as long as you are on Windows 10 and have winget installed,
Please put this message back.

2021-11-17 15:36 UTC, vedantmgoyal2009 commented on README.md
> -So before you download this module and put it in your modules folder, make sure to do ` Install-Module powershell-yaml; Install-Module -Name 'Carbon' `
I wrote something similar here.

https://github.com/vedantmgoyal2009/WinGetHelpers/blob/patch-1/README.md?plain=1#L14-L17

2021-11-17 15:38 UTC, vedantmgoyal2009 commented on WinGetHelpers.psm1
> +        ManifestVersion   = "1.0.0";
That's a part of OTBS indentation. I didn't do it manually. VS Code automatically did it.

2021-11-17 15:52 UTC, vedantmgoyal2009 commented on README.md
> -So before you download this module and put it in your modules folder, make sure to do ` Install-Module powershell-yaml; Install-Module -Name 'Carbon' `
https://github.com/jedieaston/WinGetHelpers/pull/4/commits/78f3a48c1144055b2095b5d0695ab9d05998fe8a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R18-R21

2021-11-17 15:52 UTC, vedantmgoyal2009 commented on README.md
> -So before you download this module and put it in your modules folder, make sure to do ` Install-Module powershell-yaml; Install-Module -Name 'Carbon' `
https://github.com/vedantmgoyal2009/WinGetHelpers/blob/patch-1/README.md?plain=1#L18-L21

2021-11-17 15:53 UTC, vedantmgoyal2009 commented on README.md
> -So before you download this module and put it in your modules folder, make sure to do ` Install-Module powershell-yaml; Install-Module -Name 'Carbon' `
Please refer to the last one. The above two are outdated.

2021-11-17 15:56 UTC, vedantmgoyal2009 commented
@jedieaston I've made the changes to the documentation. However, I have changed the language a bit.

2021-11-17 16:08 UTC, jedieaston requested changes
two quick things and I'll merge.

2021-11-17 16:08 UTC, jedieaston commented on README.md
> +I hastily made this PowerShell module, that contains a collection of helper functions to make creation/submission of manifests easy for [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkg
```suggestion
I hastily made this PowerShell module, that contains a collection of helper functions to make creation/submission of manifests easy for [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs). Maybe it will be useful for you too.
```

2021-11-17 16:08 UTC, jedieaston commented on README.md
> +__Now updated for 1.0 manifests__
```suggestion
__Now updated for 1.0 manifests!__
```

2021-11-17 17:27 UTC, jedieaston approved these changes

2021-11-17 17:28 UTC, merged

2021-12-05 08:17 UTC, vedantmgoyal2009 commented
@jedieaston please accept the invitation on LinkedIn 🙏🏻